name: CI Pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build
        env:
          DATABASE_URL: file:local.db
          ANTHROPIC_API_KEY: dummy_key

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type checking
        run: pnpm run check

      - name: Run linting
        run: pnpm run lint_ci

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm run test:run
        env:
          DATABASE_URL: file:local.db
          ANTHROPIC_API_KEY: dummy_key

  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.1-jammy
    strategy:
      fail-fast: false
      matrix:
        test-suite: [basic, visual]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build
        env:
          DATABASE_URL: file:local.db
          ANTHROPIC_API_KEY: dummy_key

      - name: Run Basic E2E tests
        if: matrix.test-suite == 'basic'
        run: pnpm run test:e2e --grep "TodoApp - Basic Functionality"
        env:
          CI: true
          DATABASE_URL: file:local.db
          ANTHROPIC_API_KEY: dummy_key

      - name: Run Visual tests
        if: matrix.test-suite == 'visual'
        run: pnpm run test:visual
        env:
          CI: true
          HOME: /root
          DATABASE_URL: file:local.db
          ANTHROPIC_API_KEY: dummy_key

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.test-suite }}
          path: playwright-report/
          retention-days: 30
