name: Generate Visual Snapshots

on:
  workflow_dispatch:

jobs:
  generate-snapshots:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build
        env:
          DATABASE_URL: file:local.db
          ANTHROPIC_API_KEY: dummy_key

      - name: Generate Linux snapshots
        run: pnpm run test:visual --update-snapshots
        env:
          CI: true
          HOME: /root
          DATABASE_URL: file:local.db
          ANTHROPIC_API_KEY: dummy_key

      - name: Upload snapshots
        uses: actions/upload-artifact@v4
        with:
          name: linux-snapshots
          path: e2e/**/*-linux.png
          retention-days: 30
